### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by jens-png** [Geo1088/mc-capture-the-flag#2]
Hello 

Ive read the readme file and i dont undestand how to set up the game. Pls help

**Comment by eritbh** [comment]
Hi, this is a WIP pack and doesn't really have a user-friendly way of setting it up at the moment. I'd have to check what you use to spawn in flags, it's been a while since I've worked on this.

**Comment by jens-png** [comment]
Yeah i looked in to it and this is much above my ability, very nice work thougth.
